BookingSystemDls.Web/Models/ErrorViewModel.cs
namespace BookingSystemDls.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookingSystemDls.Web/Controllers/BookingCodeController.cs
using BookingSystemDls.DataModel.BookingCode;
using BookingSystemDls.Provider.Abstraction;
using Microsoft.AspNetCore.Mvc;

namespace BookingSystemDls.Web.Controllers
{
    public class BookingCodeController : Controller
    {
        private IBookingCodeProvider _bookingCodeProvider;

        public BookingCodeController(IBookingCodeProvider bookingCodeService)
        {
            this._bookingCodeProvider = bookingCodeService;
        }

        public IActionResult Index(int page = 1, int displayData = 5)
        {
            var dataModel = _bookingCodeProvider.GetAll(page, displayData);
            ViewBag.TotalPage = dataModel.TotalPage;
            ViewBag.TotalData = dataModel.TotalData;
            ViewBag.Page = page;
            ViewBag.DisplayData = displayData;
            ViewBag.DataFrom = ((page - 1) * displayData) + 1;
            ViewBag.DataTo = (displayData * page < dataModel.TotalData) ? displayData * page : dataModel.TotalData;
            return View(dataModel);
        }

        public IActionResult UpsertForm(string? code)
        {
            var dataModel = code == null ? new BookingCodeUpsertDataModel() : _bookingCodeProvider.GetUpdate(code);
            return View(dataModel);
        }

        [HttpPost]
        public IActionResult Insert(BookingCodeUpsertDataModel dataModel)
        {
            _bookingCodeProvider.Insert(dataModel);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(BookingCodeUpsertDataModel dataModel)
        {
            _bookingCodeProvider.Update(dataModel);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string code)
        {
            _bookingCodeProvider.Delete(code);
            return RedirectToAction("Index");
        }
    }
}

BookingSystemDls.Web/Controllers/ResourceController.cs
using BookingSystemDls.DataModel.Resource;
using BookingSystemDls.Provider.Abstraction;
using Microsoft.AspNetCore.Mvc;

namespace BookingSystemDls.Web.Controllers
{
    public class ResourceController : Controller
    {
        private IResourceProvider _resourceProvider;
        private IResourceCodeProvider _resourceCodeProvider;

        public ResourceController(IResourceProvider resourceProvider, IResourceCodeProvider resourceCodeProvider)
        {
            this._resourceProvider = resourceProvider;
            this._resourceCodeProvider = resourceCodeProvider;
        }

        public IActionResult Index(int page = 1, int displayData = 5)
        {
            var dataModel = _resourceProvider.GetAll(page, displayData);
            ViewBag.TotalPage = dataModel.TotalPage;
            ViewBag.TotalData = dataModel.TotalData;
            ViewBag.Page = page;
            ViewBag.DisplayData = displayData;
            ViewBag.DataFrom = ((page - 1) * displayData) + 1;
            ViewBag.DataTo = (displayData * page < dataModel.TotalData) ? displayData * page : dataModel.TotalData;
            return View(dataModel);
        }

        public IActionResult Upsertform(int? id)
        {
            var dataModel = id == null ? new ResourceUpsertDataModel() : _resourceProvider.GetUpdate(id.Value);
            return View(dataModel);
        }

        public IActionResult Upsert(ResourceUpsertDataModel dataModel)
        {
            _resourceProvider.Upsert(dataModel);
            if (dataModel.ResourceCodes != null) _resourceCodeProvider.Upsert(dataModel.ResourceCodes);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _resourceProvider.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

BookingSystemDls.Web/Controllers/RoomController.cs
using BookingSystemDls.DataModel.Room;
using BookingSystemDls.Provider.Abstraction;
using Microsoft.AspNetCore.Mvc;

namespace BookingSystemDls.Web.Controllers
{
    public class RoomController : Controller
    {
        private IRoomProvider _roomProvider;
        private IDropdownProvider _dropdownProvider;

        public RoomController(IRoomProvider roomProvider, IDropdownProvider dropdownProvider)
        {
            this._roomProvider = roomProvider;
            this._dropdownProvider = dropdownProvider;
        }

        public IActionResult Index(int page = 1, int displayData = 5)
        {
            var dataModel = _roomProvider.GetAll(page, displayData);
            ViewBag.TotalPage = dataModel.TotalPage;
            ViewBag.TotalData = dataModel.TotalData;
            ViewBag.Page = page;
            ViewBag.DisplayData = displayData;
            ViewBag.DataFrom = ((page - 1) * displayData) + 1;
            ViewBag.DataTo = (displayData * page < dataModel.TotalData) ? displayData * page : dataModel.TotalData;
            return View(dataModel);
        }

        public IActionResult UpsertForm(int id)
        {
            var dataModel = id == 0 ? new RoomUpsertDataModel() : _roomProvider.GetUpdate(id);
            ViewBag.LocationDropdown = _dropdownProvider.GetLocationDropdown();
            return View(dataModel);
        }

        public IActionResult Upsert(RoomUpsertDataModel dataModel)
        {
            return RedirectToAction("Index");
        }
    }
}

BookingSystemDls.Web/Views/BookingCode/Index.cshtml
@using BookingSystemDls.DataModel.BookingCode
@model BookingCodeDataModel

@{
    ViewData["Title"] = "Booking Code";
}

<div class="table-index">
    <a class="regular-button" asp-controller="BookingCode" asp-action="UpsertForm">Add New</a>
    <table class="regular-table">
        <thead>
            <tr>
                <th>Action</th>
                <th>Booking Code</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.IndexDataModels)
            {
                <tr>
                    <td>
                        <a asp-controller="BookingCode" asp-action="UpsertForm" asp-route-code="@row.Code">
                            <i class="fa-solid fa-pencil"></i>
                        </a>
                        <a asp-controller="BookingCode" asp-action="Delete" asp-route-code="@row.Code">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                    <td>@row.Code</td>
                </tr>
            }
    </table>
    <div class="regular-pagination">
        <div class="navigation">
            <div class="page">
                @if (ViewBag.Page > 1)
                {
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-page="1" asp-route-displaData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-page="@((int)ViewBag.Page - 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                <p>@ViewBag.Page</p>
                @if (ViewBag.Page < ViewBag.TotalPage)
                {
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-page="@((int)ViewBag.Page + 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-page="@ViewBag.TotalPage" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
            </div>
            <div class="regular-dropdown">
                <div class="select">
                    <p>@ViewBag.DisplayData</p>
                    <i class="fa-solid fa-chevron-down"></i>
                </div>
                <div class="option">
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-displayData="5">5</a>
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-displayData="10">10</a>
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-displayData="15">15</a>
                    <a asp-controller="BookingCode" asp-action="Index" asp-route-displayData="20">20</a>
                </div>
            </div>
        </div>
        <div class="info">
            <p>@ViewBag.DataFrom - @ViewBag.DataTo of @ViewBag.TotalData item</p>
        </div>
    </div>
</div>

BookingSystemDls.Web/Views/BookingCode/UpsertForm.cshtml
@using BookingSystemDls.DataModel.BookingCode
@model BookingCodeUpsertDataModel

@{
    ViewData["Title"] = Model.Code == null ? "Add New Booking Code" : "Update " + Model.Code;
    string action = Model.Code == null ? "Insert" : "Update";
}

<div class="booking-code-upsert-form">
    <form class="regular-form" method="post" asp-controller="BookingCode" asp-action=@action>
        <div class="regular-input">
            <p>Booking Code</p>
            @if (Model.Code == null)
            {
                <input class="text" type="text" asp-for="Code" />
            }
            else
            {
                <input class="text" type="text" placeholder=@Model.Code disabled />
                <input type="hidden" asp-for="Code" />
            }
        </div>
        <div class="regular-input">
            <p>Status</p>
            <input type="checkbox" asp-for="Status" />
        </div>
        <div class="regular-input">
            <p></p>
            <div class="button-group">
                <button class="regular-button" type="submit">Submit</button>
                <a class="regular-button" asp-controller="BookingCode" asp-action="Index">Back</a>
            </div>
        </div>
    </form>
</div>

BookingSystemDls.Web/Views/Resource/Index.cshtml
@using BookingSystemDls.DataModel.Resource
@model ResourceDataModel

@{
    ViewData["Title"] = "Resource";
}

<div class="table-index">
    <a class="regular-button" asp-controller="Resource" asp-action="UpsertForm">Add New</a>
    <table class="regular-table">
        <thead>
            <tr>
                <th>Action</th>
                <th>Resource Name</th>
                <th>Status</th>
                <th>Icon</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.IndexDataModels)
            {
                <tr>
                    <td>
                        <a asp-controller="Resource" asp-action="UpsertForm" asp-route-id="@row.Id">
                            <i class="fa-solid fa-pencil"></i>
                        </a>
                        <a asp-controller="Resource" asp-action="Delete" asp-route-id="@row.Id">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                    <td>@row.Name</td>
                    <td><input type="checkbox" disabled asp-for=@row.Status /></td>
                    <td>
                        <img src="~/upload/@row.Icon" />
                    </td>
                </tr>
            }
    </table>
    <div class="regular-pagination">
        <div class="navigation">
            <div class="page">
                @if (ViewBag.Page > 1)
                {
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="1" asp-route-displaData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@((int)ViewBag.Page - 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                <p>@ViewBag.Page</p>
                @if (ViewBag.Page < ViewBag.TotalPage)
                {
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@((int)ViewBag.Page + 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@ViewBag.TotalPage" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
            </div>
            <div class="regular-dropdown">
                <div class="select">
                    <p>@ViewBag.DisplayData</p>
                    <i class="fa-solid fa-chevron-down"></i>
                </div>
                <div class="option">
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="5">5</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="10">10</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="15">15</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="20">20</a>
                </div>
            </div>
        </div>
        <div class="info">
            <p>@ViewBag.DataFrom - @ViewBag.DataTo of @ViewBag.TotalData item</p>
        </div>
    </div>
</div>

BookingSystemDls.Web/Views/Resource/UpsertForm.cshtml
@using BookingSystemDls.DataModel.Resource
@model ResourceUpsertDataModel

@{
    ViewData["Title"] = Model.Id == 0 ? "Add New Resource" : "Update " + Model.Name;
}

<div class="resource-upsert-form">
    <form class="regular-form" method="post" enctype="multipart/form-data" asp-controller="Resource" asp-action="Upsert">
        <input class="resource-id" type="hidden" asp-for="Id" />
        <div class="regular-input">
            <p>Resource Name</p>
            <input class="text" type="text" asp-for="Name" />
        </div>
        @if (Model.Id != 0)
        {
            <div class="regular-input">
                <p>Resource Code</p>
                <div class="resource-code-list">
                    <a class="regular-button add-new-button">Add New</a>
                    <table class="regular-table">
                        <thead>
                            <tr>
                                <th>Is Active</th>
                                <th>Resource Code</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.ResourceCodes.Count; i++)
                            {
                                <tr>
                                    <input type="hidden" name="ResourceCodes[@i].Code" asp-for="@Model.ResourceCodes[i].Code" />
                                    <input type="hidden" name="ResourceCodes[@i].ResourceId" asp-for="@Model.ResourceCodes[i].ResourceId" />
                                    <td>
                                        <input type="checkbox" name="ResourceCodes[@i].Status" asp-for="@Model.ResourceCodes[i].Status" />
                                    </td>
                                    <td>@Model.ResourceCodes[i].Code</td>
                                </tr>
                            }
                    </table>
                </div>
            </div>
        }
        <div class="regular-input">
            <p>Status</p>
            <input type="checkbox" asp-for="Status" />
        </div>
        <div class="regular-input">
            <p>Resource Icon</p>
            <div class="file-group">
                @if (Model.Id != 0)
                {
                    <img src="~/upload/@Model.Icon" />
                }
                <div>
                    <label class="regular-button" for="file">Browse</label>
                    <p class="file-path">@Model.Icon</p>
                </div>
                <input id="file" type="file" asp-for="IconFile" />
            </div>
        </div>
        <div class="regular-input">
            <p></p>
            <div class="button-group">
                <button class="regular-button" type="submit">Submit</button>
                <a class="regular-button" asp-controller="Resource" asp-action="Index">Back</a>
            </div>
        </div>
    </form>
    <div class="popup-container">
        <div class="form-popup resource-code-upsert-form-popup">
            <div class="regular-input">
                <p>Resource Code</p>
                <input id="code" class="text" type="text" />
            </div>
            <div class="regular-input">
                <p>Status</p>
                <input id="status" type="checkbox" />
            </div>
            <div class="regular-input">
                <p></p>
                <div class="button-group">
                    <button class="regular-button submit-button" type="submit">Submit</button>
                    <button class="regular-button close-popup-button">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>

BookingSystemDls.Web/Views/Room/Index.cshtml
@using BookingSystemDls.DataModel.Room
@model RoomDataModel

@{
    ViewData["Title"] = "Room";
}

<div class="table-index">
    <a class="regular-button" asp-controller="Room" asp-action="UpsertForm">Add New</a>
    <table class="regular-table">
        <thead>
            <tr>
                <th>Action</th>
                <th>Room Name</th>
                <th>Floor</th>
                <th>Description</th>
                <th>Location Office</th>
                <th>Capacity</th>
                <th>Room Color</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var row in Model.IndexDataModels)
            {
                <tr>
                    <td>
                        <a asp-controller="Room" asp-action="UpsertForm" asp-route-id="@row.Id">
                            <i class="fa-solid fa-pencil"></i>
                        </a>
                        <a asp-controller="Room" asp-action="Delete" asp-route-id="@row.Id">
                            <i class="fa-solid fa-trash"></i>
                        </a>
                    </td>
                    <td>@row.Name</td>
                    <td>@row.Floor</td>
                    <td>@row.Description</td>
                    <td>@row.Location</td>
                    <td>@row.Capacity</td>
                    <td class="flex-cell">
                        <i class="fa-solid fa-bookmark" style="color:@row.Color"></i>
                        <p>@row.Color</p>
                    </td>
                </tr>
            }
    </table>
    <div class="regular-pagination">
        <div class="navigation">
            <div class="page">
                @if (ViewBag.Page > 1)
                {
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="1" asp-route-displaData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@((int)ViewBag.Page - 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-backward-step"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-caret-left"></i>
                    </a>
                }
                <p>@ViewBag.Page</p>
                @if (ViewBag.Page < ViewBag.TotalPage)
                {
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@((int)ViewBag.Page + 1)" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-page="@ViewBag.TotalPage" asp-route-displayData="@ViewBag.DisplayData">
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
                else
                {
                    <a>
                        <i class="fa-solid fa-caret-right"></i>
                    </a>
                    <a>
                        <i class="fa-solid fa-forward-step"></i>
                    </a>
                }
            </div>
            <div class="regular-dropdown">
                <div class="select">
                    <p>@ViewBag.DisplayData</p>
                    <i class="fa-solid fa-chevron-down"></i>
                </div>
                <div class="option">
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="5">5</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="10">10</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="15">15</a>
                    <a asp-controller="Resource" asp-action="Index" asp-route-displayData="20">20</a>
                </div>
            </div>
        </div>
        <div class="info">
            <p>@ViewBag.DataFrom - @ViewBag.DataTo of @ViewBag.TotalData item</p>
        </div>
    </div>
</div>

BookingSystemDls.Web/Views/Room/UpsertForm.cshtml
@using BookingSystemDls.DataModel.Room
@model RoomUpsertDataModel

@{
    ViewData["Title"] = Model.Id == 0 ? "Add New Room" : "Update " + Model.Name;
}

<div class="booking-code-upsert-form">
    <form class="regular-form" method="post" asp-controller="Room" asp-action="Upsert">
        <input class="hidden" type="text" asp-for="Id" />
        <div class="regular-input">
            <p>Room Name</p>
            <input class="text" type="text" asp-for="Name" />
        </div>
        <div class="regular-input">
            <p>Floor</p>
            <input class="text" type="number" asp-for="Floor" />
        </div>
        <div class="regular-input">
            <p>Description</p>
            <input class="text" type="text" asp-for="Description" />
        </div>
        <div class="regular-input">
            <p>Location</p>
            <select class="text" asp-for="LocationId">
                <option value="null">Location</option>
                @foreach (var row in ViewBag.LocationDropdown)
                {
                    <option value="@row.Value">@row.Label</option>
                }
            </select>
        </div>
        <div class="regular-input">
            <p>Capacity</p>
            <input class="text" type="number" asp-for="Capacity" />
        </div>
        @if (Model.Id != 0)
        {
            <div class="regular-input">
                <p>Resource</p>
                <div class="resource-code-list">
                    <table class="regular-table">
                        <thead>
                            <tr>
                                <th>Is Active</th>
                                <th>Resource Code</th>
                            </tr>
                        </thead>
                        <tbody>
                            @for (int i = 0; i < Model.RoomResources.Count; i++)
                            {
                                <tr>
                                    <td>
                                        <input type="checkbox" name="RoomResources[@i].IsChecked" asp-for="@Model.RoomResources[i].IsChecked" />
                                    </td>
                                    <td>@Model.RoomResources[i].ResourceName</td>
                                </tr>
                            }
                    </table>
                </div>
            </div>
        }
        <div class="regular-input">
            <p></p>
            <div class="button-group">
                <button class="regular-button" type="submit">Submit</button>
                <a class="regular-button" asp-controller="Room" asp-action="Index">Back</a>
            </div>
        </div>
    </form>
</div>

BookingSystemDls.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Booking System DLS</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>
<body>
    <div class="container">
        <div class="header">
            <div class="main-header">
                <h1>SPECTRUM</h1>
                <div class="profile">
                    <p>Welcome,</p>
                    <p>Guest as guest</p>
                </div>
                <div class="date">
                    <i class="fa-solid fa-calendar-days"></i>
                    <p>Senin, 17 Maret 2020</p>
                </div>
                <a class="logout" href="#">
                    <i class="fa-solid fa-power-off"></i>
                    <p>Logout</p>
                </a>
            </div>
            <div class="sub-header">
                <h2>@ViewData["Title"]</h2>
            </div>
        </div>
        <div class="aside">
            <h1>Kino</h1>
            <div class="navbar">
                <p class="header">Master Data</p>
                <a class="body" asp-controller="BookingCode" asp-action="Index">Master Booking Code</a>
                <a class="body" asp-controller="Resource" asp-action="Index">Master Resource</a>
                <a class="body" asp-controller="Room" asp-action="Index">Master Room</a>
                <p class="header">Transaction</p>
                <a class="body">History</a>
                <a class="body">Report</a>
            </div>
        </div>
        <div class="main">
            @RenderBody()
        </div>
    </div>
</body>
<script src="~/js/site.js"></script>
</html>